server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://47.97.196.216/bookstore
    username: root
    password: '@0314qwer'
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl